# Generated by Django 2.2 on 2019-04-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Verbos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('verb', models.CharField(max_length=50)),
                ('meaning', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
